# Generated by Django 6.0.2 on 2026-03-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Musicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('spotify', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
